### ISSUE TITLE
bootstrap3-phpstorm-plugin does not work on Pycharm

### ISSUE THREAD

**Issue by luzfcb** [JasonMortonNZ/bootstrap3-phpstorm-plugin#1]
Given that the basis of the JetBrains IDE's is the same, in theory should work in PyCharm. Is there any special configuration that make it work with PyCharm?

**Comment by JasonMortonNZ** [comment]
What version of PyCharm are you using?

**Comment by luzfcb** [comment]
Latest version, 3.1 and 3.1.1

**Comment by JasonMortonNZ** [comment]
I'll be updating this plugin over the weekend and recompiling with JDK 1.6. Hoping that should solve you issues.
