### ISSUE TITLE
Is the plugin still maintained?

### ISSUE THREAD

**Issue by dandv** [JasonMortonNZ/bootstrap3-phpstorm-plugin#10]
I see a fork at https://github.com/bodiam/intellij-bootstrap3

CC @bodiam

Where do I contribute?

**Comment by JasonMortonNZ** [comment]
I'll be updating this plugin over the weekend and recompiling with JDK 1.6. Hoping that should solve you issues.

**Comment by dandv** [comment]
Just checking if the plugin has been updated.
