### ISSUE TITLE
How to?

### ISSUE THREAD

**Issue by ghost** [JasonMortonNZ/bootstrap3-phpstorm-plugin#3]
How to use it?

i write bs3-table press tab and it placed me a

```
<bs3-table></bs3-table>
```

**Comment by sbarre** [comment]
I am having the same issue.  None of these live templates triggers seem to be working for me in PhpStorm 7.1.2 on OS X.   I get the same result as above, it just expands into a tag.

**Comment by devvyn** [comment]
As a workaround, for anyone interested, I was able to copy the Bootstrap.xml file from the repo to the appropriate path as specified in http://www.jetbrains.com/phpstorm/webhelp/live-templates.html. Restart and the Bootstrap3 group shows up in Preferences > Live Templates.

**Comment by dandv** [comment]
`bs3-table` now expands perfectly in the latest WebStorm EAP. @JasonMortonNZ, feel free to close.

**Comment by JasonMortonNZ** [comment]
Look's like you might have the expand XML setting checked in your IDE settings.
