### ISSUE TITLE
Doesn't create templates or template group in WebStorm 7.0.3

### ISSUE THREAD

**Issue by devvyn** [JasonMortonNZ/bootstrap3-phpstorm-plugin#4]
Even though the plugin is listed in the plugin repository for WebStorm, no templates get saved when the plugin is installed. I checked the templates path (as documented in http://www.jetbrains.com/phpstorm/webhelp/live-templates.html) and confirmed there was no Bootstrap.xml or anything else added.

**Comment by devvyn** [comment]
Workaround: drop the Bootstrap.xml from the git repo into the appropriate path on the dev machine and restart WebStorm. Probably the same workaround for other jetBrains IDEs.

**Comment by ryentzer** [comment]
This works for me. Thanks for posting.

**Comment by lucasff** [comment]
I have a more problematic issue. All my live templates goes away while the plugin was enabled. After uninstalling they are back.
