### ISSUE TITLE
install issue

### ISSUE THREAD

**Issue by alienfactory** [JasonMortonNZ/bootstrap3-phpstorm-plugin#5]
HI 
i am having some issues with your plugin. when i download and install from phpstorm
your plugin seems to be removing all my live templates and does not install your bootstrap templates. when this happens i have to reset everything by clearing 
HOME/Library/Preferences/WebIde40"
HOME/Library/Caches/WebIde40"
/Library/Application Support/WebIde40"
/Library/Logs/WebIde40"

i am trying to install on a mac. I also installed on a pc and had no issues 

here is my discussion on phpstorms board
http://devnet.jetbrains.com/message/5513996#5513996

**Comment by melihucar** [comment]
I have same issue. Works perfectly on windows 7 but my cannot use on my mac.

Edit: for a temporary solution without installing plugin I copied bootstrap.xml to ~/Library/Preferences/WebIde70/templates and worked

**Comment by dandv** [comment]
Works perfectly out of he box in the latest WebStorm EAP.
