### ISSUE TITLE
Unsupported major.minor Version

### ISSUE THREAD

**Issue by mikebronner** [JasonMortonNZ/bootstrap3-phpstorm-plugin#6]
Got this error today using PHPStorm 8 EAP:

> 9:47:20 AM PicoPluginExtensionInitializationException: com/jasonnz/bootstrap/BootstapTemplatesProvider : Unsupported major.minor version 51.0 [Plugin: com.jasonnz.bootstrap]

**Comment by AustinW** [comment]
:+1:

**Comment by freefcw** [comment]
+1 I meet the problem in the same version

**Comment by drfraker** [comment]
Same issue here.

**Comment by ryentzer** [comment]
Same as well. It looks like the plugin installer doesn't work as expected.

**Comment by maxisoft-git** [comment]
plugin works fine, the problem is that  phpstorm 8 EAP uses Java SDK 1.6  to be started, you can change the version 1.7
      <key>JVMVersion</key>
      <string>1.7*</string>

**Comment by D1no** [comment]
Mac Webstorm 9 EAP, same issue - way to fix?
// for now: uninstalled plugin, copied bootstrap.xml by hand into   ~/Library/Preferences/WebStorm9/templates/

**Comment by mollerjorge** [comment]
Same issue in Webstorm 9 EAP as D1no, was able to fix it with D1no solution.

thx!!

**Comment by JasonMortonNZ** [comment]
I'll be updating this plugin over the weekend and recompiling with JDK 1.6. Hoping that should solve you issues.
